name: Test1

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
#    - name: Install dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install -r requirements.txt
    - name: Run tests
      run: |
        python -m ./tests/test1.py



# name: Bacic Test: This is the name of your workflow. It's displayed on GitHub when the actions are running.
# on: [push]: This specifies the event that triggers the workflow. In this case, the workflow runs whenever a push is made to the repository.
#jobs:: This section contains all the jobs that the workflow will run. Jobs run in parallel by default.
#test: This is the identifier for the job. You can name it anything you like.
#runs-on: ubuntu-latest: This specifies the type of runner that the job will run on. In this case, it's the latest version of Ubuntu.
#steps:: This section contains all the steps that the job will run. Steps run in the order that they appear in the file.
#- uses: actions/checkout@v2: This step checks out your repository so the workflow can access its contents.
#- name: Set up Python: This is a descriptive name for the step.
#uses: actions/setup-python@v2: This step sets up Python on the runner. The @v2 is the version of the setup-python action to use.
#with: python-version: '3.x': This specifies the version of Python to set up.
#- name: Install dependencies: This is another descriptive name for the step.
#run: | python -m pip install --upgrade pip pip install -r requirements.txt: This step upgrades pip and installs the Python dependencies specified in the requirements.txt file.
#- name: Run tests: This is a descriptive name for the step.
#run: | python -m test.py: This step runs the test.py script.